### ISSUE TITLE
Attribute Error on first run after install

### ISSUE THREAD

**Issue by dunz0r** [rymdlego/vquery#1]
**Expected result**
Vq shows the help text

**Actual result**
Vq throws an error

**Output**
$ vq --help
Traceback (most recent call last):
  File "/usr/local/bin/vq", line 39, in <module>
    from vquery import *
  File "/usr/local/lib/python2.7/dist-packages/vquery/__init__.py", line 4, in <module>
    from .vqconnect import setup_connection
  File "/usr/local/lib/python2.7/dist-packages/vquery/vqconnect.py", line 24, in <module>
    context = ssl.create_default_context()
AttributeError: 'module' object has no attribute 'create_default_context'

**Version information**
Python 2.7.6
Latest version of vq installed via pip

**Comment by rymdlego** [comment]
Seems to be an issue for many python-projects utilizing SSL context creation, as those methods were introduced in Python 2.7.9

Suggested solution is to run vq in Python3 or upgrade Python2. Thanks for bringing it to attention though - I'll add it to documentation.
